spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: search-and-listing
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka